{
 "title": "Kubernetes Deployment Statefulset Daemonset metrics",
 "tags": [
  "kubernetes",
  "deployment",
  "statefulset",
  "daemonset"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Deployment", "query": { "query": "label_values(deployment)" } },
   { "name": "Statefulset", "query": { "query": "label_values(statefulset)" } },
   { "name": "Daemonset", "query": { "query": "label_values(daemonset)" } },
   { "name": "Node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  {
   "title": "Deployment CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\", node=~\"^$Node$\", container!=\"\"}[2m])) / sum (kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\", node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\", node=~\"^$Node$\", container!=\"\"}) / sum (kube_pod_container_resource_requests{resource=\"memory\",pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\",node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))) - ((sum(kube_deployment_status_replicas_available{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)))) / ((sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\", node=~\"^$Node$\", container!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\", node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\", node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\", node=~\"^$Node$\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"memory\",pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\",node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"memory\",pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\",node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Available (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas_available{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Total (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))",
     "legendFormat": "{{ $Daemonset }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\", node=~\"^$Node$\",container!=\"\"}[1m])) by (pod, node)",
     "legendFormat": "real: {{ pod }}"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\", node=~\"^$Node$\"}) by (pod,node)",
     "legendFormat": "rqst: {{ pod }}"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\", node=~\"^$Node$\"}) by (pod,node)",
     "legendFormat": "limit: {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\", node=~\"^$Node$\", container!=\"\"}) by (pod,node)",
     "legendFormat": "real: {{pod}}"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"memory\",pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\",node=~\"^$Node$\"}) by (pod,node)",
     "legendFormat": "rqst: {{ pod }}"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"memory\",pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\",node=~\"^$Node$\"}) by (pod,node)",
     "legendFormat": "limit: {{ pod }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (kubelet_volume_stats_used_bytes{node=~\"^$Node$\", persistentvolumeclaim=~\".*$Deployment$Statefulset$Daemonset.*$\"} / kubelet_volume_stats_capacity_bytes{node=~\"^$Node$\", persistentvolumeclaim=~\".*$Deployment$Statefulset$Daemonset.*$\"})",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\",node=~\"^$Node$\"}[1m])) by (pod, node)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum( rate (container_network_transmit_bytes_total{id!=\"/\",pod=~\"^$Deployment$Statefulset$Daemonset-[a-z0-9]*(-[a-z0-9]*)?$\",node=~\"^$Node$\"}[1m])) by (pod, node)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  }
 ]
}